spring:
  datasource:
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  error:
    include-message: always
